/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.inf_schauer.apollo_kotlin.apollo_example

import java.util.*

fun main() {
    val id = UUID.fromString("4cfe25a2-529e-432e-be08-87ee9094774a")
    ProductServices.details(id)
    ProductServices.create("Test", listOf(111,222,333))
}
